// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package core

import (
	"strconv"
)

var ArchNames = map[int32]string{
	1:  "amd64",
	5:  "arm",
	6:  "arm64",
	10: "wasm",
}

var ArchValues = map[string]Arch{
	"amd64": Arch_ARCH_AMD64,
	"arm":   Arch_ARCH_ARM,
	"arm64": Arch_ARCH_ARM64,
	"wasm":  Arch_ARCH_WASM,
}

func (x Arch) Format() string {
	s, ok := ArchNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x *Arch) Parse(value string) error {
	if x != nil {
		s, ok := ArchValues[value]
		if ok {
			*x = s
		} else {
			*x = Arch_ARCH_AMD64
		}
	} else {
		*x = Arch_ARCH_AMD64
	}
	return nil
}
