// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/core/boxed.proto

package core

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BoxedBool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxedBool) Reset()         { *m = BoxedBool{} }
func (m *BoxedBool) String() string { return proto.CompactTextString(m) }
func (*BoxedBool) ProtoMessage()    {}
func (*BoxedBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d6ceface8d8610, []int{0}
}
func (m *BoxedBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxedBool.Unmarshal(m, b)
}
func (m *BoxedBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxedBool.Marshal(b, m, deterministic)
}
func (m *BoxedBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxedBool.Merge(m, src)
}
func (m *BoxedBool) XXX_Size() int {
	return xxx_messageInfo_BoxedBool.Size(m)
}
func (m *BoxedBool) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxedBool.DiscardUnknown(m)
}

var xxx_messageInfo_BoxedBool proto.InternalMessageInfo

func (m *BoxedBool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Strings struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Strings) Reset()         { *m = Strings{} }
func (m *Strings) String() string { return proto.CompactTextString(m) }
func (*Strings) ProtoMessage()    {}
func (*Strings) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d6ceface8d8610, []int{1}
}
func (m *Strings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strings.Unmarshal(m, b)
}
func (m *Strings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strings.Marshal(b, m, deterministic)
}
func (m *Strings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strings.Merge(m, src)
}
func (m *Strings) XXX_Size() int {
	return xxx_messageInfo_Strings.Size(m)
}
func (m *Strings) XXX_DiscardUnknown() {
	xxx_messageInfo_Strings.DiscardUnknown(m)
}

var xxx_messageInfo_Strings proto.InternalMessageInfo

func (m *Strings) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Integers struct {
	Values               []int64  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Integers) Reset()         { *m = Integers{} }
func (m *Integers) String() string { return proto.CompactTextString(m) }
func (*Integers) ProtoMessage()    {}
func (*Integers) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d6ceface8d8610, []int{2}
}
func (m *Integers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integers.Unmarshal(m, b)
}
func (m *Integers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integers.Marshal(b, m, deterministic)
}
func (m *Integers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integers.Merge(m, src)
}
func (m *Integers) XXX_Size() int {
	return xxx_messageInfo_Integers.Size(m)
}
func (m *Integers) XXX_DiscardUnknown() {
	xxx_messageInfo_Integers.DiscardUnknown(m)
}

var xxx_messageInfo_Integers proto.InternalMessageInfo

func (m *Integers) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type Doubles struct {
	Values               []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Doubles) Reset()         { *m = Doubles{} }
func (m *Doubles) String() string { return proto.CompactTextString(m) }
func (*Doubles) ProtoMessage()    {}
func (*Doubles) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d6ceface8d8610, []int{3}
}
func (m *Doubles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Doubles.Unmarshal(m, b)
}
func (m *Doubles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Doubles.Marshal(b, m, deterministic)
}
func (m *Doubles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doubles.Merge(m, src)
}
func (m *Doubles) XXX_Size() int {
	return xxx_messageInfo_Doubles.Size(m)
}
func (m *Doubles) XXX_DiscardUnknown() {
	xxx_messageInfo_Doubles.DiscardUnknown(m)
}

var xxx_messageInfo_Doubles proto.InternalMessageInfo

func (m *Doubles) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*BoxedBool)(nil), "mojo.core.BoxedBool")
	proto.RegisterType((*Strings)(nil), "mojo.core.Strings")
	proto.RegisterType((*Integers)(nil), "mojo.core.Integers")
	proto.RegisterType((*Doubles)(nil), "mojo.core.Doubles")
}

func init() { proto.RegisterFile("mojo/core/boxed.proto", fileDescriptor_68d6ceface8d8610) }

var fileDescriptor_68d6ceface8d8610 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xcd, 0xcf, 0xca,
	0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x4f, 0xca, 0xaf, 0x48, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x04, 0x09, 0xeb, 0x81, 0x84, 0x95, 0xcc, 0xb8, 0x38, 0x9d, 0x40, 0x32, 0x4e,
	0xf9, 0xf9, 0x39, 0x42, 0x9a, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x1c, 0x4e, 0xc2, 0xaf, 0xee, 0xc9, 0xf3, 0x83, 0x05, 0x74, 0xf2, 0x73, 0x33, 0x4b, 0x52,
	0x73, 0x0b, 0x4a, 0x2a, 0x83, 0x20, 0x2a, 0x94, 0xcc, 0xb9, 0xd8, 0x83, 0x4b, 0x8a, 0x32, 0xf3,
	0xd2, 0x8b, 0x85, 0x74, 0xb8, 0xd8, 0xc0, 0x62, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x4e,
	0x22, 0xaf, 0xee, 0xc9, 0x0b, 0x40, 0x44, 0x90, 0xf4, 0x41, 0xd5, 0x28, 0x59, 0x70, 0x71, 0x78,
	0xe6, 0x95, 0xa4, 0xa6, 0xa7, 0x16, 0xa1, 0xeb, 0x64, 0x26, 0xa0, 0xd3, 0x9c, 0x8b, 0xdd, 0x25,
	0xbf, 0x34, 0x29, 0x27, 0x15, 0x5d, 0x23, 0x23, 0x7e, 0x8d, 0x4e, 0xe1, 0x5c, 0x62, 0xf9, 0x45,
	0xe9, 0x7a, 0x20, 0x4f, 0xe7, 0x24, 0xe6, 0x41, 0x18, 0x60, 0xdf, 0x3b, 0x71, 0x81, 0xfd, 0x1e,
	0x00, 0x0a, 0x94, 0x00, 0xc6, 0x28, 0xfd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc,
	0x5c, 0x7d, 0x90, 0x1a, 0x5d, 0x90, 0x6a, 0x48, 0xe8, 0xa5, 0xe7, 0xeb, 0x17, 0x64, 0xa7, 0xeb,
	0xc3, 0x83, 0xd3, 0x1a, 0x44, 0x24, 0xb1, 0x81, 0x83, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x16, 0xb7, 0x29, 0x31, 0x67, 0x01, 0x00, 0x00,
}
