// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/core/media_type.proto

package core

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MediaType struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Subtype              string               `protobuf:"bytes,2,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Parameter            *MediaType_Parameter `protobuf:"bytes,3,opt,name=parameter,proto3" json:"parameter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MediaType) Reset()         { *m = MediaType{} }
func (m *MediaType) String() string { return proto.CompactTextString(m) }
func (*MediaType) ProtoMessage()    {}
func (*MediaType) Descriptor() ([]byte, []int) {
	return fileDescriptor_90901ff6046f3795, []int{0}
}
func (m *MediaType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaType.Unmarshal(m, b)
}
func (m *MediaType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaType.Marshal(b, m, deterministic)
}
func (m *MediaType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaType.Merge(m, src)
}
func (m *MediaType) XXX_Size() int {
	return xxx_messageInfo_MediaType.Size(m)
}
func (m *MediaType) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaType.DiscardUnknown(m)
}

var xxx_messageInfo_MediaType proto.InternalMessageInfo

func (m *MediaType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MediaType) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *MediaType) GetParameter() *MediaType_Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

type MediaType_Parameter struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaType_Parameter) Reset()         { *m = MediaType_Parameter{} }
func (m *MediaType_Parameter) String() string { return proto.CompactTextString(m) }
func (*MediaType_Parameter) ProtoMessage()    {}
func (*MediaType_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_90901ff6046f3795, []int{0, 0}
}
func (m *MediaType_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaType_Parameter.Unmarshal(m, b)
}
func (m *MediaType_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaType_Parameter.Marshal(b, m, deterministic)
}
func (m *MediaType_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaType_Parameter.Merge(m, src)
}
func (m *MediaType_Parameter) XXX_Size() int {
	return xxx_messageInfo_MediaType_Parameter.Size(m)
}
func (m *MediaType_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaType_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_MediaType_Parameter proto.InternalMessageInfo

func (m *MediaType_Parameter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MediaType_Parameter) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*MediaType)(nil), "mojo.core.MediaType")
	proto.RegisterType((*MediaType_Parameter)(nil), "mojo.core.MediaType.Parameter")
}

func init() { proto.RegisterFile("mojo/core/media_type.proto", fileDescriptor_90901ff6046f3795) }

var fileDescriptor_90901ff6046f3795 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xe9, 0xe6, 0x1f, 0x9a, 0xe1, 0x74, 0x19, 0xd3, 0xd1, 0x83, 0x1d, 0x0a, 0xb2, 0x83,
	0x26, 0x30, 0x8f, 0xbb, 0xf5, 0x2e, 0x14, 0x51, 0x0f, 0x7a, 0x90, 0x76, 0x86, 0x5a, 0xbb, 0x98,
	0x50, 0x53, 0xa1, 0x5f, 0xc9, 0x0f, 0x95, 0x0f, 0x90, 0x4f, 0x21, 0x6f, 0xd6, 0xa5, 0xb9, 0x14,
	0x9a, 0xe7, 0xf7, 0x0b, 0x4f, 0xde, 0x17, 0x45, 0x5c, 0x7c, 0x09, 0xba, 0x11, 0x35, 0xa3, 0x9c,
	0x7d, 0x94, 0xd9, 0xbb, 0x6a, 0x25, 0x23, 0xb2, 0x16, 0x4a, 0xe0, 0x10, 0x32, 0x02, 0x59, 0x34,
	0xeb, 0xb1, 0xdf, 0x6c, 0xdb, 0x74, 0xc4, 0xd5, 0xdf, 0x00, 0x85, 0x0f, 0xa0, 0x3d, 0xb5, 0x92,
	0xe1, 0x1b, 0x74, 0x00, 0xf6, 0x3c, 0x58, 0x04, 0xcb, 0x30, 0xc1, 0x46, 0xc7, 0x63, 0xf8, 0xbf,
	0x15, 0xbc, 0x54, 0x8c, 0x4b, 0xd5, 0x3e, 0xda, 0x1c, 0x53, 0x74, 0xfc, 0xd3, 0xe4, 0x16, 0x1d,
	0x58, 0x74, 0x66, 0x74, 0x3c, 0xe9, 0x8e, 0x3c, 0x7a, 0x4f, 0xe1, 0x67, 0x14, 0xca, 0xac, 0xce,
	0x38, 0x53, 0xac, 0x9e, 0x0f, 0x17, 0xc1, 0x72, 0xb4, 0xba, 0x24, 0xae, 0x1c, 0x71, 0x0d, 0x48,
	0xba, 0xa7, 0x92, 0x0b, 0xa3, 0xe3, 0xa9, 0x93, 0xbc, 0x4b, 0xfb, 0x9b, 0x22, 0x8e, 0x42, 0x27,
	0xe0, 0x6b, 0x34, 0xac, 0x58, 0xdb, 0x75, 0x9f, 0x18, 0x1d, 0x9f, 0x54, 0xac, 0xf5, 0x3c, 0x48,
	0xf1, 0x1a, 0x1d, 0xda, 0xe7, 0xdb, 0xde, 0xa3, 0xd5, 0x99, 0x57, 0xe2, 0x05, 0xce, 0x93, 0xa9,
	0xd1, 0xf1, 0xa9, 0x45, 0x3c, 0x75, 0xe7, 0x24, 0x6f, 0xe8, 0x5c, 0xd4, 0x85, 0x55, 0xb6, 0xd9,
	0x77, 0xd1, 0xbb, 0xc9, 0xd8, 0xbd, 0x20, 0x85, 0xb1, 0xa6, 0xc1, 0x2b, 0x2d, 0x4a, 0xf5, 0xd9,
	0xe4, 0x64, 0x23, 0x38, 0x05, 0xee, 0x0e, 0x8c, 0xdd, 0xfc, 0x0b, 0x41, 0x65, 0x55, 0x50, 0xb7,
	0x90, 0x35, 0x7c, 0xf2, 0x23, 0xbb, 0x90, 0xfb, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x59,
	0xf0, 0x56, 0xd0, 0x01, 0x00, 0x00,
}
