// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package core

import (
	"strconv"
)

var OSNames = map[int32]string{
	1:  "android",
	2:  "darwin",
	6:  "ios",
	10: "linux",
	20: "windows",
}

var OSValues = map[string]OS{
	"android": OS_OS_ANDROID,
	"darwin":  OS_OS_DARWIN,
	"ios":     OS_OS_IOS,
	"linux":   OS_OS_LINUX,
	"windows": OS_OS_WINDOWS,
}

func (x OS) Format() string {
	s, ok := OSNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x *OS) Parse(value string) error {
	if x != nil {
		s, ok := OSValues[value]
		if ok {
			*x = s
		} else {
			*x = OS_OS_ANDROID
		}
	} else {
		*x = OS_OS_ANDROID
	}
	return nil
}
