// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/core/template_string.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TemplateString struct {
	Segments             []*TemplateString_Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                    `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                     `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *TemplateString) Reset()         { *m = TemplateString{} }
func (m *TemplateString) String() string { return proto.CompactTextString(m) }
func (*TemplateString) ProtoMessage()    {}
func (*TemplateString) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dff1d10a014c394, []int{0}
}
func (m *TemplateString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateString.Unmarshal(m, b)
}
func (m *TemplateString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateString.Marshal(b, m, deterministic)
}
func (m *TemplateString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateString.Merge(m, src)
}
func (m *TemplateString) XXX_Size() int {
	return xxx_messageInfo_TemplateString.Size(m)
}
func (m *TemplateString) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateString.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateString proto.InternalMessageInfo

func (m *TemplateString) GetSegments() []*TemplateString_Segment {
	if m != nil {
		return m.Segments
	}
	return nil
}

type TemplateString_Segment struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Templated            bool     `protobuf:"varint,2,opt,name=templated,proto3" json:"templated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *TemplateString_Segment) Reset()         { *m = TemplateString_Segment{} }
func (m *TemplateString_Segment) String() string { return proto.CompactTextString(m) }
func (*TemplateString_Segment) ProtoMessage()    {}
func (*TemplateString_Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dff1d10a014c394, []int{0, 0}
}
func (m *TemplateString_Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateString_Segment.Unmarshal(m, b)
}
func (m *TemplateString_Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateString_Segment.Marshal(b, m, deterministic)
}
func (m *TemplateString_Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateString_Segment.Merge(m, src)
}
func (m *TemplateString_Segment) XXX_Size() int {
	return xxx_messageInfo_TemplateString_Segment.Size(m)
}
func (m *TemplateString_Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateString_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateString_Segment proto.InternalMessageInfo

func (m *TemplateString_Segment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TemplateString_Segment) GetTemplated() bool {
	if m != nil {
		return m.Templated
	}
	return false
}

func init() {
	proto.RegisterType((*TemplateString)(nil), "mojo.core.TemplateString")
	proto.RegisterType((*TemplateString_Segment)(nil), "mojo.core.TemplateString.Segment")
}

func init() { proto.RegisterFile("mojo/core/template_string.proto", fileDescriptor_1dff1d10a014c394) }

var fileDescriptor_1dff1d10a014c394 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0xcd, 0xcf, 0xca,
	0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x2f, 0x49, 0xcd, 0x2d, 0xc8, 0x49, 0x2c, 0x49, 0x8d, 0x2f,
	0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x29, 0xd0,
	0x03, 0x29, 0x50, 0xba, 0xc5, 0xc8, 0xc5, 0x17, 0x02, 0x55, 0x14, 0x0c, 0x56, 0x23, 0x14, 0xca,
	0xc5, 0x51, 0x9c, 0x9a, 0x9e, 0x9b, 0x9a, 0x57, 0x52, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d,
	0xa4, 0xa8, 0x07, 0xd7, 0xa0, 0x87, 0xaa, 0x58, 0x2f, 0x18, 0xa2, 0xd2, 0x49, 0xec, 0xd5, 0x3d,
	0x79, 0x21, 0x98, 0x36, 0x9d, 0xfc, 0xdc, 0x4c, 0x90, 0xcd, 0x25, 0x95, 0x41, 0x70, 0xa3, 0xa4,
	0x0a, 0xb9, 0xd8, 0xa1, 0x8a, 0x85, 0xf4, 0xb9, 0xd8, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x9d, 0x44, 0x5f, 0xdd, 0x93, 0x17, 0x84, 0x0a, 0x21, 0x69,
	0x86, 0xa9, 0x12, 0x32, 0xe5, 0xe2, 0x84, 0xf9, 0x24, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0xc3,
	0x49, 0xfc, 0xd5, 0x3d, 0x79, 0x61, 0xb8, 0x20, 0x92, 0x26, 0x84, 0x4a, 0xa7, 0x94, 0x19, 0x8f,
	0xe5, 0x18, 0xb8, 0xc4, 0xf2, 0x8b, 0xd2, 0xc1, 0x1e, 0xc8, 0x49, 0xcc, 0x4b, 0x47, 0xf8, 0xc4,
	0x49, 0x18, 0xd5, 0x2b, 0x01, 0xa0, 0xa0, 0x09, 0x60, 0x8c, 0xd2, 0x4f, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x07, 0x29, 0xd6, 0x05, 0x69, 0x83, 0x84, 0x66, 0x7a, 0xbe,
	0x7e, 0x41, 0x76, 0xba, 0x3e, 0x3c, 0x78, 0xad, 0x41, 0x44, 0x12, 0x1b, 0x38, 0x50, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x03, 0x6c, 0x63, 0x77, 0x01, 0x00, 0x00,
}
