// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/core/time.proto

package core

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Month int32

const (
	Month_MONTH_UNSPECIFIED Month = 0
	Month_MONTH_JANUARY     Month = 1
	Month_MONTH_FEBRUARY    Month = 2
	Month_MONTH_MARCH       Month = 3
	Month_MONTH_APRIL       Month = 4
	Month_MONTH_MAY         Month = 5
	Month_MONTH_JUNE        Month = 6
	Month_MONTH_JULY        Month = 7
	Month_MONTH_AUGUST      Month = 8
	Month_MONTH_SEPTEMBER   Month = 9
	Month_MONTH_OCTOBER     Month = 10
	Month_MONTH_NOVEMBER    Month = 11
	Month_MONTH_DECEMBER    Month = 12
)

var Month_name = map[int32]string{
	0:  "MONTH_UNSPECIFIED",
	1:  "MONTH_JANUARY",
	2:  "MONTH_FEBRUARY",
	3:  "MONTH_MARCH",
	4:  "MONTH_APRIL",
	5:  "MONTH_MAY",
	6:  "MONTH_JUNE",
	7:  "MONTH_JULY",
	8:  "MONTH_AUGUST",
	9:  "MONTH_SEPTEMBER",
	10: "MONTH_OCTOBER",
	11: "MONTH_NOVEMBER",
	12: "MONTH_DECEMBER",
}

var Month_value = map[string]int32{
	"MONTH_UNSPECIFIED": 0,
	"MONTH_JANUARY":     1,
	"MONTH_FEBRUARY":    2,
	"MONTH_MARCH":       3,
	"MONTH_APRIL":       4,
	"MONTH_MAY":         5,
	"MONTH_JUNE":        6,
	"MONTH_JULY":        7,
	"MONTH_AUGUST":      8,
	"MONTH_SEPTEMBER":   9,
	"MONTH_OCTOBER":     10,
	"MONTH_NOVEMBER":    11,
	"MONTH_DECEMBER":    12,
}

func (x Month) String() string {
	return proto.EnumName(Month_name, int32(x))
}

func (Month) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{0}
}

type DayOfWeek int32

const (
	DayOfWeek_DAY_OF_WEEK_UNSPECIFIED DayOfWeek = 0
	DayOfWeek_DAY_OF_WEEK_MONDAY      DayOfWeek = 1
	DayOfWeek_DAY_OF_WEEK_TUESDAY     DayOfWeek = 2
	DayOfWeek_DAY_OF_WEEK_WEDNESDAY   DayOfWeek = 3
	DayOfWeek_DAY_OF_WEEK_THURSDAY    DayOfWeek = 4
	DayOfWeek_DAY_OF_WEEK_FRIDAY      DayOfWeek = 5
	DayOfWeek_DAY_OF_WEEK_SATURDAY    DayOfWeek = 6
	DayOfWeek_DAY_OF_WEEK_SUNDAY      DayOfWeek = 7
)

var DayOfWeek_name = map[int32]string{
	0: "DAY_OF_WEEK_UNSPECIFIED",
	1: "DAY_OF_WEEK_MONDAY",
	2: "DAY_OF_WEEK_TUESDAY",
	3: "DAY_OF_WEEK_WEDNESDAY",
	4: "DAY_OF_WEEK_THURSDAY",
	5: "DAY_OF_WEEK_FRIDAY",
	6: "DAY_OF_WEEK_SATURDAY",
	7: "DAY_OF_WEEK_SUNDAY",
}

var DayOfWeek_value = map[string]int32{
	"DAY_OF_WEEK_UNSPECIFIED": 0,
	"DAY_OF_WEEK_MONDAY":      1,
	"DAY_OF_WEEK_TUESDAY":     2,
	"DAY_OF_WEEK_WEDNESDAY":   3,
	"DAY_OF_WEEK_THURSDAY":    4,
	"DAY_OF_WEEK_FRIDAY":      5,
	"DAY_OF_WEEK_SATURDAY":    6,
	"DAY_OF_WEEK_SUNDAY":      7,
}

func (x DayOfWeek) String() string {
	return proto.EnumName(DayOfWeek_name, int32(x))
}

func (DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{1}
}

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{0}
}
func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type DateTime struct {
	Year                 int32     `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32     `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32     `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour                 int32     `protobuf:"varint,4,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute               int32     `protobuf:"varint,5,opt,name=minute,proto3" json:"minute,omitempty"`
	Seconds              int64     `protobuf:"varint,6,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds          int32     `protobuf:"varint,7,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	TimeZone             *TimeZone `protobuf:"bytes,15,opt,name=time_zone,json=timeZone,proto3" json:"timeZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DateTime) Reset()         { *m = DateTime{} }
func (m *DateTime) String() string { return proto.CompactTextString(m) }
func (*DateTime) ProtoMessage()    {}
func (*DateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{1}
}
func (m *DateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTime.Unmarshal(m, b)
}
func (m *DateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTime.Marshal(b, m, deterministic)
}
func (m *DateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTime.Merge(m, src)
}
func (m *DateTime) XXX_Size() int {
	return xxx_messageInfo_DateTime.Size(m)
}
func (m *DateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTime.DiscardUnknown(m)
}

var xxx_messageInfo_DateTime proto.InternalMessageInfo

func (m *DateTime) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *DateTime) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *DateTime) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *DateTime) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *DateTime) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *DateTime) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *DateTime) GetNanoseconds() int32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

func (m *DateTime) GetTimeZone() *TimeZone {
	if m != nil {
		return m.TimeZone
	}
	return nil
}

type TimeZone struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeZone) Reset()         { *m = TimeZone{} }
func (m *TimeZone) String() string { return proto.CompactTextString(m) }
func (*TimeZone) ProtoMessage()    {}
func (*TimeZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{2}
}
func (m *TimeZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeZone.Unmarshal(m, b)
}
func (m *TimeZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeZone.Marshal(b, m, deterministic)
}
func (m *TimeZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeZone.Merge(m, src)
}
func (m *TimeZone) XXX_Size() int {
	return xxx_messageInfo_TimeZone.Size(m)
}
func (m *TimeZone) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeZone.DiscardUnknown(m)
}

var xxx_messageInfo_TimeZone proto.InternalMessageInfo

func (m *TimeZone) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *TimeZone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds          int32    `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{3}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanoseconds() int32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type Duration struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds          int32    `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{4}
}
func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Duration) GetNanoseconds() int32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type TimeOfDay struct {
	Hours                int32    `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes              int32    `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	Seconds              int32    `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,4,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeOfDay) Reset()         { *m = TimeOfDay{} }
func (m *TimeOfDay) String() string { return proto.CompactTextString(m) }
func (*TimeOfDay) ProtoMessage()    {}
func (*TimeOfDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeef1e239c433ed4, []int{5}
}
func (m *TimeOfDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOfDay.Unmarshal(m, b)
}
func (m *TimeOfDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOfDay.Marshal(b, m, deterministic)
}
func (m *TimeOfDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOfDay.Merge(m, src)
}
func (m *TimeOfDay) XXX_Size() int {
	return xxx_messageInfo_TimeOfDay.Size(m)
}
func (m *TimeOfDay) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOfDay.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOfDay proto.InternalMessageInfo

func (m *TimeOfDay) GetHours() int32 {
	if m != nil {
		return m.Hours
	}
	return 0
}

func (m *TimeOfDay) GetMinutes() int32 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

func (m *TimeOfDay) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *TimeOfDay) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterEnum("mojo.core.Month", Month_name, Month_value)
	proto.RegisterEnum("mojo.core.DayOfWeek", DayOfWeek_name, DayOfWeek_value)
	proto.RegisterType((*Date)(nil), "mojo.core.Date")
	proto.RegisterType((*DateTime)(nil), "mojo.core.DateTime")
	proto.RegisterType((*TimeZone)(nil), "mojo.core.TimeZone")
	proto.RegisterType((*Timestamp)(nil), "mojo.core.Timestamp")
	proto.RegisterType((*Duration)(nil), "mojo.core.Duration")
	proto.RegisterType((*TimeOfDay)(nil), "mojo.core.TimeOfDay")
}

func init() { proto.RegisterFile("mojo/core/time.proto", fileDescriptor_aeef1e239c433ed4) }

var fileDescriptor_aeef1e239c433ed4 = []byte{
	// 714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xcf, 0x6e, 0xda, 0x4e,
	0x10, 0xc7, 0x7f, 0xe6, 0x3f, 0x43, 0x12, 0xcc, 0x12, 0x12, 0x47, 0xbf, 0x03, 0x11, 0x95, 0xaa,
	0x24, 0x4a, 0x41, 0x6a, 0x8f, 0x39, 0x61, 0x6c, 0x0a, 0x6d, 0xb0, 0x91, 0xb1, 0x13, 0x91, 0x0b,
	0x75, 0x12, 0x43, 0x68, 0x6a, 0x2f, 0x02, 0x23, 0xd5, 0x3d, 0xf4, 0x19, 0xfa, 0x4e, 0x7d, 0x89,
	0x9e, 0xfc, 0x00, 0x7e, 0x82, 0x1e, 0xab, 0xdd, 0x35, 0xf1, 0x96, 0x43, 0xa5, 0xf6, 0xd0, 0x5e,
	0x2c, 0xcd, 0x67, 0xbe, 0xe3, 0xf9, 0xb3, 0x63, 0x2f, 0xec, 0xbb, 0xf8, 0x3d, 0x6e, 0xdd, 0xe1,
	0xa5, 0xd3, 0xf2, 0xe7, 0xae, 0xd3, 0x5c, 0x2c, 0xb1, 0x8f, 0x51, 0x91, 0xd0, 0x26, 0xa1, 0x8d,
	0xcf, 0x90, 0x51, 0x6c, 0xdf, 0x41, 0xcf, 0x21, 0x13, 0x38, 0xf6, 0x52, 0x12, 0x8e, 0x85, 0x93,
	0xac, 0x8c, 0xa2, 0xb0, 0xbe, 0x47, 0xec, 0x73, 0xec, 0xce, 0x7d, 0xc7, 0x5d, 0xf8, 0x81, 0x41,
	0xfd, 0xe8, 0x14, 0xb2, 0x2e, 0xf6, 0xfc, 0x07, 0x29, 0x45, 0x85, 0xd5, 0x28, 0xac, 0x97, 0x29,
	0xe0, 0x94, 0x4c, 0x81, 0x9e, 0x41, 0xfa, 0xde, 0x0e, 0xa4, 0x34, 0x15, 0x56, 0xa2, 0xb0, 0xbe,
	0x7b, 0x6f, 0x07, 0x9c, 0x8c, 0x78, 0x1b, 0x5f, 0xd2, 0x50, 0x20, 0x05, 0x98, 0x73, 0xf7, 0x9f,
	0x15, 0x41, 0xf2, 0x3e, 0xe0, 0xf5, 0x52, 0xca, 0x24, 0x79, 0x89, 0xcd, 0xe7, 0x25, 0x36, 0x3a,
	0x87, 0x9c, 0x3b, 0xf7, 0xd6, 0xbe, 0x23, 0x65, 0xa9, 0x72, 0x3f, 0x0a, 0xeb, 0x22, 0x23, 0x9c,
	0x36, 0xd6, 0xa0, 0x16, 0xe4, 0x57, 0xce, 0x1d, 0xf6, 0xee, 0x57, 0x52, 0xee, 0x58, 0x38, 0x49,
	0xcb, 0xb5, 0x28, 0xac, 0x57, 0x62, 0xc4, 0xe9, 0x37, 0x2a, 0x74, 0x01, 0x25, 0xcf, 0xf6, 0xf0,
	0x26, 0x28, 0x4f, 0x73, 0x1c, 0x45, 0x61, 0xbd, 0xc6, 0x61, 0x2e, 0x90, 0x57, 0xa3, 0x1e, 0x14,
	0xc9, 0x09, 0x4f, 0x3e, 0x61, 0xcf, 0x91, 0xca, 0xc7, 0xc2, 0x49, 0xe9, 0x65, 0xb5, 0xf9, 0x74,
	0xce, 0x4d, 0x32, 0xdf, 0x1b, 0xec, 0x39, 0xf2, 0x41, 0x14, 0xd6, 0x91, 0x1f, 0x5b, 0xdc, 0xcb,
	0x0a, 0x1b, 0xd6, 0x78, 0x07, 0x85, 0x8d, 0x9a, 0x74, 0x8c, 0xa7, 0xd3, 0x95, 0xe3, 0xc7, 0x67,
	0x42, 0x3b, 0x66, 0x84, 0xef, 0x98, 0x11, 0x32, 0x47, 0xcf, 0x76, 0x1d, 0x7a, 0x2c, 0x45, 0x36,
	0x47, 0x62, 0xf3, 0x73, 0x24, 0x76, 0x23, 0x80, 0x22, 0xc9, 0xb0, 0xf2, 0x6d, 0x77, 0xc1, 0x8f,
	0x49, 0xf8, 0x93, 0x31, 0xa5, 0x7e, 0x67, 0x4c, 0x8d, 0x8f, 0x50, 0x50, 0xd6, 0x4b, 0xdb, 0x9f,
	0x63, 0xef, 0x2f, 0x67, 0xfe, 0x2a, 0xb0, 0xae, 0xf5, 0xa9, 0x62, 0x07, 0x64, 0x85, 0xc9, 0x4a,
	0xad, 0xe2, 0xb9, 0xd2, 0x15, 0xa6, 0x80, 0x5f, 0x61, 0x0a, 0x48, 0x99, 0x6c, 0xa3, 0x36, 0x19,
	0x69, 0x99, 0x31, 0xe2, 0xcb, 0x8c, 0x11, 0xdf, 0x57, 0x3a, 0x09, 0xf8, 0x45, 0x5f, 0xa7, 0x90,
	0xa5, 0x95, 0xc6, 0x1f, 0x00, 0x2d, 0x86, 0x02, 0xbe, 0x18, 0x0a, 0xce, 0xbe, 0x0b, 0x90, 0x1d,
	0xd0, 0x2f, 0xab, 0x06, 0x95, 0x81, 0xae, 0x99, 0xbd, 0x89, 0xa5, 0x8d, 0x86, 0x6a, 0xa7, 0xdf,
	0xed, 0xab, 0x8a, 0xf8, 0x1f, 0xaa, 0xc0, 0x2e, 0xc3, 0x6f, 0xda, 0x9a, 0xd5, 0x36, 0xc6, 0xa2,
	0x80, 0x10, 0xec, 0x31, 0xd4, 0x55, 0x65, 0x83, 0xb2, 0x14, 0x2a, 0x43, 0x89, 0xb1, 0x41, 0xdb,
	0xe8, 0xf4, 0xc4, 0x74, 0x02, 0xda, 0x43, 0xa3, 0x7f, 0x29, 0x66, 0xd0, 0x2e, 0x14, 0x37, 0x8a,
	0xb1, 0x98, 0x45, 0x7b, 0x00, 0xf1, 0x7b, 0x2d, 0x4d, 0x15, 0x73, 0xbc, 0x7d, 0x39, 0x16, 0xf3,
	0x48, 0x84, 0x9d, 0x38, 0xde, 0x7a, 0x6d, 0x8d, 0x4c, 0xb1, 0x80, 0xaa, 0x50, 0x66, 0x64, 0xa4,
	0x0e, 0x4d, 0x75, 0x20, 0xab, 0x86, 0x58, 0x4c, 0xca, 0xd3, 0x3b, 0xa6, 0x4e, 0x10, 0x24, 0xe5,
	0x69, 0xfa, 0x15, 0x93, 0x95, 0x12, 0xa6, 0xa8, 0x1d, 0xc6, 0x76, 0xce, 0xbe, 0x09, 0x50, 0x54,
	0xec, 0x40, 0x9f, 0x5e, 0x3b, 0xce, 0x23, 0xfa, 0x1f, 0x0e, 0x95, 0xf6, 0x78, 0xa2, 0x77, 0x27,
	0xd7, 0xaa, 0xfa, 0x76, 0x6b, 0x08, 0x07, 0x80, 0x78, 0xe7, 0x40, 0xd7, 0x94, 0x36, 0x99, 0xc4,
	0x21, 0x54, 0x79, 0x6e, 0x5a, 0xea, 0x88, 0x38, 0x52, 0xe8, 0x08, 0x6a, 0xbc, 0xe3, 0x5a, 0x55,
	0x34, 0xe6, 0x4a, 0x23, 0x09, 0xf6, 0x7f, 0x8a, 0xe9, 0x59, 0x06, 0xf5, 0x64, 0xb6, 0xb3, 0x74,
	0x8d, 0xbe, 0x42, 0x47, 0xb5, 0x15, 0x31, 0x6a, 0x9b, 0x96, 0x41, 0x3c, 0xb9, 0xed, 0x88, 0x91,
	0x45, 0xeb, 0xca, 0xcb, 0x57, 0x70, 0x80, 0x97, 0x33, 0xfa, 0xbb, 0xf8, 0x60, 0x7b, 0xb3, 0xe4,
	0xbf, 0x21, 0xd3, 0x95, 0x1d, 0x92, 0x5b, 0x63, 0x28, 0xdc, 0xb4, 0x66, 0x73, 0xff, 0x61, 0x7d,
	0xdb, 0xbc, 0xc3, 0x6e, 0x8b, 0x48, 0x5e, 0x10, 0x31, 0xbb, 0x5d, 0x66, 0xb8, 0xb5, 0x78, 0x9c,
	0xb5, 0x9e, 0xae, 0x9b, 0x0b, 0xf2, 0xb8, 0xcd, 0xd1, 0xfb, 0xe6, 0xd5, 0x8f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0x7b, 0x5b, 0x0d, 0x87, 0x06, 0x00, 0x00,
}
