// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/core/url.proto

package core

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Url struct {
	Scheme               string         `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Authority            *Url_Authority `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Path                 string         `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query                *Url_Query     `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Fragment             string         `protobuf:"bytes,7,opt,name=fragment,proto3" json:"fragment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Url) Reset()         { *m = Url{} }
func (m *Url) String() string { return proto.CompactTextString(m) }
func (*Url) ProtoMessage()    {}
func (*Url) Descriptor() ([]byte, []int) {
	return fileDescriptor_2799ce1b059c4724, []int{0}
}
func (m *Url) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Url.Unmarshal(m, b)
}
func (m *Url) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Url.Marshal(b, m, deterministic)
}
func (m *Url) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Url.Merge(m, src)
}
func (m *Url) XXX_Size() int {
	return xxx_messageInfo_Url.Size(m)
}
func (m *Url) XXX_DiscardUnknown() {
	xxx_messageInfo_Url.DiscardUnknown(m)
}

var xxx_messageInfo_Url proto.InternalMessageInfo

func (m *Url) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *Url) GetAuthority() *Url_Authority {
	if m != nil {
		return m.Authority
	}
	return nil
}

func (m *Url) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Url) GetQuery() *Url_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Url) GetFragment() string {
	if m != nil {
		return m.Fragment
	}
	return ""
}

type Url_Authority struct {
	UserInfo             string   `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"userInfo,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int64    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Url_Authority) Reset()         { *m = Url_Authority{} }
func (m *Url_Authority) String() string { return proto.CompactTextString(m) }
func (*Url_Authority) ProtoMessage()    {}
func (*Url_Authority) Descriptor() ([]byte, []int) {
	return fileDescriptor_2799ce1b059c4724, []int{0, 0}
}
func (m *Url_Authority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Url_Authority.Unmarshal(m, b)
}
func (m *Url_Authority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Url_Authority.Marshal(b, m, deterministic)
}
func (m *Url_Authority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Url_Authority.Merge(m, src)
}
func (m *Url_Authority) XXX_Size() int {
	return xxx_messageInfo_Url_Authority.Size(m)
}
func (m *Url_Authority) XXX_DiscardUnknown() {
	xxx_messageInfo_Url_Authority.DiscardUnknown(m)
}

var xxx_messageInfo_Url_Authority proto.InternalMessageInfo

func (m *Url_Authority) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

func (m *Url_Authority) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Url_Authority) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Url_Query struct {
	Values               map[string]*Url_Query_Strings `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Url_Query) Reset()         { *m = Url_Query{} }
func (m *Url_Query) String() string { return proto.CompactTextString(m) }
func (*Url_Query) ProtoMessage()    {}
func (*Url_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_2799ce1b059c4724, []int{0, 1}
}
func (m *Url_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Url_Query.Unmarshal(m, b)
}
func (m *Url_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Url_Query.Marshal(b, m, deterministic)
}
func (m *Url_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Url_Query.Merge(m, src)
}
func (m *Url_Query) XXX_Size() int {
	return xxx_messageInfo_Url_Query.Size(m)
}
func (m *Url_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Url_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Url_Query proto.InternalMessageInfo

func (m *Url_Query) GetValues() map[string]*Url_Query_Strings {
	if m != nil {
		return m.Values
	}
	return nil
}

type Url_Query_Strings struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Url_Query_Strings) Reset()         { *m = Url_Query_Strings{} }
func (m *Url_Query_Strings) String() string { return proto.CompactTextString(m) }
func (*Url_Query_Strings) ProtoMessage()    {}
func (*Url_Query_Strings) Descriptor() ([]byte, []int) {
	return fileDescriptor_2799ce1b059c4724, []int{0, 1, 0}
}
func (m *Url_Query_Strings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Url_Query_Strings.Unmarshal(m, b)
}
func (m *Url_Query_Strings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Url_Query_Strings.Marshal(b, m, deterministic)
}
func (m *Url_Query_Strings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Url_Query_Strings.Merge(m, src)
}
func (m *Url_Query_Strings) XXX_Size() int {
	return xxx_messageInfo_Url_Query_Strings.Size(m)
}
func (m *Url_Query_Strings) XXX_DiscardUnknown() {
	xxx_messageInfo_Url_Query_Strings.DiscardUnknown(m)
}

var xxx_messageInfo_Url_Query_Strings proto.InternalMessageInfo

func (m *Url_Query_Strings) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Url)(nil), "mojo.core.Url")
	proto.RegisterType((*Url_Authority)(nil), "mojo.core.Url.Authority")
	proto.RegisterType((*Url_Query)(nil), "mojo.core.Url.Query")
	proto.RegisterMapType((map[string]*Url_Query_Strings)(nil), "mojo.core.Url.Query.ValuesEntry")
	proto.RegisterType((*Url_Query_Strings)(nil), "mojo.core.Url.Query.Strings")
}

func init() { proto.RegisterFile("mojo/core/url.proto", fileDescriptor_2799ce1b059c4724) }

var fileDescriptor_2799ce1b059c4724 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcf, 0xea, 0xd3, 0x40,
	0x10, 0x26, 0x8d, 0xe9, 0xef, 0x97, 0x29, 0xfe, 0xdb, 0x96, 0x1a, 0x8a, 0x90, 0xa0, 0x20, 0x3d,
	0xd4, 0x04, 0xda, 0x83, 0xa2, 0x07, 0x31, 0x20, 0xe2, 0x45, 0xab, 0x12, 0x0f, 0x5e, 0x24, 0x2d,
	0xdb, 0x24, 0x36, 0xc9, 0xc6, 0xcd, 0x46, 0xc8, 0xc9, 0x57, 0xd0, 0xb7, 0xf2, 0x29, 0xf2, 0x00,
	0x79, 0x0a, 0xd9, 0x49, 0x9a, 0xae, 0x52, 0xf0, 0x12, 0x98, 0x6f, 0xbe, 0xf9, 0x26, 0xf3, 0xcd,
	0x0e, 0x4c, 0x33, 0xf6, 0x95, 0x79, 0x7b, 0xc6, 0xa9, 0x57, 0xf1, 0xd4, 0x2d, 0x38, 0x13, 0x8c,
	0x98, 0x12, 0x74, 0x25, 0xf8, 0xe0, 0xb7, 0x01, 0x7a, 0xc0, 0x53, 0xb2, 0x82, 0x71, 0xb9, 0x8f,
	0x69, 0x46, 0x2d, 0xcd, 0xd1, 0x96, 0xa6, 0x3f, 0x6b, 0x1b, 0xfb, 0x4e, 0x87, 0xac, 0x58, 0x96,
	0x08, 0x9a, 0x15, 0xa2, 0xfe, 0xd0, 0x73, 0xc8, 0x3b, 0x30, 0xc3, 0x4a, 0xc4, 0x8c, 0x27, 0xa2,
	0xb6, 0x46, 0x8e, 0xb6, 0x9c, 0xac, 0x2d, 0x77, 0x10, 0x75, 0x03, 0x9e, 0xba, 0x2f, 0x4f, 0x79,
	0xff, 0x5e, 0xdb, 0xd8, 0xd3, 0x81, 0xae, 0xa8, 0x9d, 0x35, 0xc8, 0x23, 0xb8, 0x51, 0x84, 0x22,
	0xb6, 0x74, 0x6c, 0x4e, 0xda, 0xc6, 0xbe, 0x25, 0x63, 0x85, 0x8c, 0x79, 0xf2, 0x02, 0x8c, 0x6f,
	0x15, 0xe5, 0xb5, 0x65, 0x60, 0xd3, 0xd9, 0x3f, 0x4d, 0xdf, 0xcb, 0x9c, 0x3f, 0x6d, 0x1b, 0xfb,
	0x36, 0xd2, 0x94, 0xfa, 0xae, 0x8e, 0xac, 0xe1, 0xfa, 0xc0, 0xc3, 0x28, 0xa3, 0xb9, 0xb0, 0xae,
	0xb0, 0xd9, 0xbc, 0x6d, 0x6c, 0x72, 0xc2, 0x94, 0x82, 0x81, 0xb7, 0xf8, 0xa9, 0x81, 0x39, 0x8c,
	0x43, 0x36, 0x60, 0x56, 0x25, 0xe5, 0x5f, 0x92, 0xfc, 0xc0, 0x7a, 0xb3, 0x50, 0x42, 0x82, 0x6f,
	0xf2, 0x03, 0x53, 0x25, 0x4e, 0x98, 0x9c, 0x2f, 0x66, 0xa5, 0x40, 0xaf, 0xfa, 0xf9, 0x64, 0xac,
	0xce, 0x27, 0x63, 0xf4, 0x81, 0x71, 0x81, 0x3e, 0xe8, 0xbd, 0x0f, 0x8c, 0xff, 0xc5, 0x93, 0xf1,
	0xe2, 0xd7, 0x08, 0x0c, 0x1c, 0x96, 0xbc, 0x85, 0xf1, 0xf7, 0x30, 0xad, 0x68, 0x69, 0x69, 0x8e,
	0xbe, 0x9c, 0xac, 0x9d, 0x4b, 0x96, 0xb8, 0x9f, 0x90, 0xf2, 0x2a, 0x17, 0xbc, 0xee, 0x56, 0xdb,
	0xd5, 0xa8, 0xab, 0xed, 0x90, 0xc5, 0x13, 0xb8, 0xfa, 0x28, 0x78, 0x92, 0x47, 0xa5, 0x7c, 0x13,
	0x8a, 0xb4, 0xf9, 0x9f, 0xc2, 0x1f, 0x30, 0x51, 0xba, 0x90, 0x87, 0xa0, 0x1f, 0x69, 0xdd, 0x1b,
	0x74, 0xb7, 0x6d, 0xec, 0x9b, 0x47, 0xaa, 0xee, 0x43, 0x66, 0xc9, 0x6b, 0x30, 0xb0, 0xba, 0x7f,
	0x43, 0xf7, 0x2f, 0xfe, 0x7b, 0xff, 0x3b, 0xdd, 0x5a, 0x91, 0xae, 0xae, 0x15, 0x81, 0x67, 0xa3,
	0xa7, 0x9a, 0x1f, 0xc0, 0x9c, 0xf1, 0x08, 0x25, 0xd2, 0x30, 0x8f, 0xce, 0x5a, 0xfe, 0x75, 0xc0,
	0xd3, 0xad, 0x7c, 0xf9, 0x5b, 0xed, 0xb3, 0x17, 0x25, 0x22, 0xae, 0x76, 0xee, 0x9e, 0x65, 0x9e,
	0x64, 0x3c, 0x96, 0xdc, 0xee, 0x40, 0x22, 0xe6, 0x15, 0xc7, 0xc8, 0x1b, 0x2e, 0xe6, 0xb9, 0xfc,
	0xec, 0xc6, 0x78, 0x33, 0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x31, 0x13, 0x9d, 0x1b, 0x4a,
	0x03, 0x00, 0x00,
}
