// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/core/value.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Object struct {
	Vals                 map[string]*Value `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44d46343c3cc16, []int{0}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetVals() map[string]*Value {
	if m != nil {
		return m.Vals
	}
	return nil
}

type Values struct {
	Vals                 []*Value `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44d46343c3cc16, []int{1}
}
func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetVals() []*Value {
	if m != nil {
		return m.Vals
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_ValuesVal
	//	*Value_ObjectVal
	//	*Value_NullVal
	//	*Value_BoolVal
	//	*Value_Int64Val
	//	*Value_DoubleVal
	//	*Value_StringVal
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44d46343c3cc16, []int{2}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_ValuesVal struct {
	ValuesVal *Values `protobuf:"bytes,1,opt,name=values_val,json=valuesVal,proto3,oneof" json:"valuesVal,omitempty"`
}
type Value_ObjectVal struct {
	ObjectVal *Object `protobuf:"bytes,2,opt,name=object_val,json=objectVal,proto3,oneof" json:"objectVal,omitempty"`
}
type Value_NullVal struct {
	NullVal *Null `protobuf:"bytes,3,opt,name=null_val,json=nullVal,proto3,oneof" json:"nullVal,omitempty"`
}
type Value_BoolVal struct {
	BoolVal bool `protobuf:"varint,4,opt,name=bool_val,json=boolVal,proto3,oneof" json:"boolVal,omitempty"`
}
type Value_Int64Val struct {
	Int64Val int64 `protobuf:"varint,5,opt,name=int64_val,json=int64Val,proto3,oneof" json:"int64Val,omitempty"`
}
type Value_DoubleVal struct {
	DoubleVal float64 `protobuf:"fixed64,6,opt,name=double_val,json=doubleVal,proto3,oneof" json:"doubleVal,omitempty"`
}
type Value_StringVal struct {
	StringVal string `protobuf:"bytes,7,opt,name=string_val,json=stringVal,proto3,oneof" json:"stringVal,omitempty"`
}

func (*Value_ValuesVal) isValue_Value() {}
func (*Value_ObjectVal) isValue_Value() {}
func (*Value_NullVal) isValue_Value()   {}
func (*Value_BoolVal) isValue_Value()   {}
func (*Value_Int64Val) isValue_Value()  {}
func (*Value_DoubleVal) isValue_Value() {}
func (*Value_StringVal) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetValuesVal() *Values {
	if x, ok := m.GetValue().(*Value_ValuesVal); ok {
		return x.ValuesVal
	}
	return nil
}

func (m *Value) GetObjectVal() *Object {
	if x, ok := m.GetValue().(*Value_ObjectVal); ok {
		return x.ObjectVal
	}
	return nil
}

func (m *Value) GetNullVal() *Null {
	if x, ok := m.GetValue().(*Value_NullVal); ok {
		return x.NullVal
	}
	return nil
}

func (m *Value) GetBoolVal() bool {
	if x, ok := m.GetValue().(*Value_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (m *Value) GetInt64Val() int64 {
	if x, ok := m.GetValue().(*Value_Int64Val); ok {
		return x.Int64Val
	}
	return 0
}

func (m *Value) GetDoubleVal() float64 {
	if x, ok := m.GetValue().(*Value_DoubleVal); ok {
		return x.DoubleVal
	}
	return 0
}

func (m *Value) GetStringVal() string {
	if x, ok := m.GetValue().(*Value_StringVal); ok {
		return x.StringVal
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_ValuesVal)(nil),
		(*Value_ObjectVal)(nil),
		(*Value_NullVal)(nil),
		(*Value_BoolVal)(nil),
		(*Value_Int64Val)(nil),
		(*Value_DoubleVal)(nil),
		(*Value_StringVal)(nil),
	}
}

func init() {
	proto.RegisterType((*Object)(nil), "mojo.core.Object")
	proto.RegisterMapType((map[string]*Value)(nil), "mojo.core.Object.ValsEntry")
	proto.RegisterType((*Values)(nil), "mojo.core.Values")
	proto.RegisterType((*Value)(nil), "mojo.core.Value")
}

func init() { proto.RegisterFile("mojo/core/value.proto", fileDescriptor_5c44d46343c3cc16) }

var fileDescriptor_5c44d46343c3cc16 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x8f, 0x93, 0x40,
	0x18, 0xc7, 0x77, 0xca, 0xf6, 0x85, 0xa7, 0xd1, 0xb5, 0xb3, 0xee, 0xda, 0xac, 0x89, 0x90, 0x7a,
	0xe1, 0xa0, 0x90, 0xd4, 0x97, 0x34, 0xee, 0x6d, 0x36, 0x26, 0x26, 0x26, 0xba, 0xd9, 0x43, 0x0f,
	0x7a, 0x30, 0x50, 0x09, 0xd2, 0x0e, 0x4c, 0x85, 0xa1, 0x09, 0xdf, 0xc4, 0x8f, 0xe3, 0x27, 0xf0,
	0x23, 0x70, 0xf1, 0xc6, 0xa7, 0x30, 0xf3, 0x4c, 0xa5, 0x58, 0xe2, 0xa5, 0x87, 0x7f, 0xff, 0xbf,
	0x1f, 0x33, 0x0f, 0x3c, 0x70, 0x91, 0x88, 0xb5, 0xf0, 0x56, 0x22, 0x0b, 0xbd, 0x9d, 0xcf, 0x8b,
	0xd0, 0xdd, 0x66, 0x42, 0x0a, 0x6a, 0xaa, 0xd8, 0x55, 0xf1, 0xd5, 0xc3, 0x43, 0x23, 0x2d, 0x38,
	0xd7, 0x85, 0xd9, 0x4f, 0x02, 0x83, 0x8f, 0xc1, 0x3a, 0x5c, 0x49, 0x7a, 0x03, 0xa7, 0x3b, 0x9f,
	0xe7, 0x53, 0x62, 0x1b, 0xce, 0x78, 0xfe, 0xd8, 0x6d, 0x50, 0x57, 0x17, 0xdc, 0xa5, 0xcf, 0xf3,
	0xb7, 0xa9, 0xcc, 0x4a, 0x46, 0xeb, 0xca, 0xba, 0xaf, 0xca, 0xcf, 0x44, 0x12, 0xcb, 0x30, 0xd9,
	0xca, 0xf2, 0x0e, 0xe1, 0xab, 0xef, 0x60, 0x36, 0x35, 0xfa, 0x14, 0x8c, 0x4d, 0x58, 0x4e, 0x89,
	0x4d, 0x1c, 0x93, 0x4d, 0xea, 0xca, 0xba, 0xb7, 0x09, 0xcb, 0x16, 0xa2, 0xfe, 0xa5, 0xd7, 0xd0,
	0xc7, 0x13, 0x4f, 0x7b, 0x36, 0x71, 0xc6, 0xf3, 0x07, 0xad, 0xe7, 0x2e, 0x55, 0xce, 0xce, 0xeb,
	0xca, 0x3a, 0xc3, 0x4a, 0x0b, 0xd5, 0xcc, 0x9b, 0xde, 0x82, 0xcc, 0x18, 0x0c, 0xb0, 0x98, 0xd3,
	0xc5, 0x3f, 0x37, 0xe8, 0x9a, 0xfe, 0x7b, 0xec, 0xd9, 0x2f, 0x03, 0xfa, 0xd8, 0xa1, 0xef, 0x01,
	0x50, 0x9d, 0x7f, 0xd9, 0xf9, 0x1c, 0x8f, 0x3e, 0x9e, 0x4f, 0x8e, 0x4d, 0x39, 0x7b, 0x54, 0x57,
	0xd6, 0xb9, 0x2e, 0x2e, 0x7d, 0x7e, 0xf0, 0xbd, 0x3b, 0xb9, 0x33, 0x9b, 0x58, 0xc9, 0x04, 0xce,
	0x0e, 0x65, 0xbd, 0x8e, 0x4c, 0x0f, 0x56, 0xcb, 0x74, 0xb1, 0x23, 0x6b, 0x62, 0x7a, 0x03, 0x23,
	0xf5, 0xe2, 0x50, 0x65, 0xa0, 0xea, 0xac, 0xa5, 0xfa, 0x50, 0x70, 0xce, 0x2e, 0xea, 0xca, 0x9a,
	0xa8, 0xd2, 0xb1, 0x66, 0xb8, 0x0f, 0xe9, 0x1c, 0x46, 0x81, 0x10, 0x5a, 0x72, 0x6a, 0x13, 0x67,
	0xa4, 0x19, 0x95, 0x75, 0x98, 0x7d, 0x48, 0x5f, 0x81, 0x19, 0xa7, 0xf2, 0xf5, 0x4b, 0x84, 0xfa,
	0x36, 0x71, 0x0c, 0x76, 0x59, 0x57, 0x16, 0xc5, 0xf0, 0x98, 0x1a, 0xfd, 0x4d, 0xe9, 0x02, 0xe0,
	0xab, 0x28, 0x02, 0x1e, 0x22, 0x37, 0xb0, 0x89, 0x43, 0xf4, 0x4d, 0x75, 0xda, 0xb9, 0x69, 0x13,
	0x2b, 0x32, 0x97, 0x59, 0x9c, 0x46, 0x48, 0x0e, 0xf1, 0xf3, 0x41, 0x52, 0xa7, 0x1d, 0xb2, 0x89,
	0xd9, 0x70, 0xff, 0x31, 0xb1, 0xcf, 0x3f, 0x7e, 0x3f, 0x39, 0x81, 0x4b, 0x91, 0x45, 0x38, 0x23,
	0xee, 0xa7, 0xd1, 0x61, 0x58, 0x0c, 0xf0, 0x2d, 0xde, 0xaa, 0x0d, 0xb8, 0x25, 0x9f, 0xbc, 0x28,
	0x96, 0xdf, 0x8a, 0xc0, 0x5d, 0x89, 0xc4, 0x53, 0x9d, 0xe7, 0xaa, 0xad, 0x37, 0x25, 0x12, 0xde,
	0x76, 0x13, 0x79, 0xcd, 0xea, 0x5c, 0xab, 0x9f, 0x60, 0x80, 0xbb, 0xf3, 0xe2, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x39, 0x3e, 0xdd, 0x94, 0x75, 0x03, 0x00, 0x00,
}
