// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojo/core/timestamp.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbb4407281c2fef, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Timestamp)(nil), "mojo.core.Timestamp")
}

func init() { proto.RegisterFile("mojo/core/timestamp.proto", fileDescriptor_5dbb4407281c2fef) }

var fileDescriptor_5dbb4407281c2fef = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0xcd, 0xcf, 0xca,
	0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x2f, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x49, 0xe9, 0x81, 0xa4, 0x94, 0xb8, 0xb9, 0x38,
	0x43, 0x60, 0xb2, 0x4e, 0x01, 0x5c, 0x62, 0xf9, 0x45, 0xe9, 0x7a, 0x20, 0xd9, 0x9c, 0xc4, 0x3c,
	0x08, 0x03, 0xac, 0xcc, 0x89, 0x23, 0xb4, 0x28, 0x27, 0x00, 0xa4, 0x37, 0x80, 0x31, 0x4a, 0x2b,
	0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xa4, 0x42, 0x17, 0xa4, 0x16,
	0x62, 0x51, 0x7a, 0xbe, 0x7e, 0x41, 0x36, 0x84, 0x6d, 0x0d, 0x22, 0x92, 0xd8, 0xc0, 0x16, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x30, 0x67, 0x93, 0x8d, 0x00, 0x00, 0x00,
}
