// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/attributes.proto

package org.mojolang.mojo.core;

public final class AttributesProto {
  private AttributesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032mojo/core/attributes.proto\022\tmojo.core*" +
      "\310\001\n\010DeclType\022\031\n\025DECL_TYPE_UNSPECIFIED\020\000\022" +
      "\022\n\016DECL_TYPE_TYPE\020\001\022\023\n\017DECL_TYPE_VALUE\020\002" +
      "\022\026\n\022DECL_TYPE_FUNCTION\020\003\022\031\n\025DECL_TYPE_CO" +
      "NSTRUCTOR\020\004\022\027\n\023DECL_TYPE_ATTRIBUTE\020\005\022\025\n\021" +
      "DECL_TYPE_PACKAGE\020\006\022\025\n\021DECL_TYPE_GENERIC" +
      "\020\007B\\\n\026org.mojolang.mojo.coreB\017Attributes" +
      "ProtoP\001Z/github.com/mojo-lang/core/go/pk" +
      "g/mojo/core;coreb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
