// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoolValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoolValues)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bool values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Boolean> getValuesList();
  /**
   * <code>repeated bool values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated bool values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  boolean getValues(int index);
}
