// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedFloatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedFloat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float val = 1;</code>
   * @return The val.
   */
  float getVal();
}
