// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedUInt32OrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedUInt32)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();
}
