// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedBytesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedBytes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
