// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedBoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedBool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool val = 1;</code>
   * @return The val.
   */
  boolean getVal();
}
