// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedInt64OrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedInt64)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
