// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   * @return The val.
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   * @return The bytes for val.
   */
  com.google.protobuf.ByteString
      getValBytes();
}
