// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface BoxedDoubleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.BoxedDouble)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double val = 1;</code>
   * @return The val.
   */
  double getVal();
}
