// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/checksum.proto

package org.mojolang.mojo.core;

public interface ChecksumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Checksum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.core.Checksum.Algorithm algorithm = 1;</code>
   * @return The enum numeric value on the wire for algorithm.
   */
  int getAlgorithmValue();
  /**
   * <code>.mojo.core.Checksum.Algorithm algorithm = 1;</code>
   * @return The algorithm.
   */
  org.mojolang.mojo.core.Checksum.Algorithm getAlgorithm();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
