// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/checksum.proto

package org.mojolang.mojo.core;

public final class ChecksumProto {
  private ChecksumProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Checksum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Checksum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030mojo/core/checksum.proto\022\tmojo.core\"\312\001" +
      "\n\010Checksum\0220\n\talgorithm\030\001 \001(\0162\035.mojo.cor" +
      "e.Checksum.Algorithm\022\r\n\005value\030\002 \001(\t\"}\n\tA" +
      "lgorithm\022\031\n\025ALGORITHM_UNSPECIFIED\020\000\022\022\n\016A" +
      "LGORITHM_MD_5\020\001\022\023\n\017ALGORITHM_SHA_1\020\002\022\025\n\021" +
      "ALGORITHM_SHA_256\020\003\022\025\n\021ALGORITHM_SHA_512" +
      "\020\004BZ\n\026org.mojolang.mojo.coreB\rChecksumPr" +
      "otoP\001Z/github.com/mojo-lang/core/go/pkg/" +
      "mojo/core;coreb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_core_Checksum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_core_Checksum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Checksum_descriptor,
        new java.lang.String[] { "Algorithm", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
