// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/color.proto

package org.mojolang.mojo.core;

public final class ColorProto {
  private ColorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Color_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Color_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025mojo/core/color.proto\022\tmojo.core\"@\n\005Co" +
      "lor\022\013\n\003red\030\001 \001(\r\022\r\n\005green\030\002 \001(\r\022\014\n\004blue\030" +
      "\003 \001(\r\022\r\n\005alpha\030\004 \001(\002BW\n\026org.mojolang.moj" +
      "o.coreB\nColorProtoP\001Z/github.com/mojo-la" +
      "ng/core/go/pkg/mojo/core;coreb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_core_Color_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_core_Color_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Color_descriptor,
        new java.lang.String[] { "Red", "Green", "Blue", "Alpha", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
