// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface FloatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Floats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Float> getValuesList();
  /**
   * <code>repeated float values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated float values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  float getValues(int index);
}
