// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/ip_address.proto

package org.mojolang.mojo.core;

public final class IpAddressProto {
  private IpAddressProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_IPv4_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_IPv4_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_IPv6_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_IPv6_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032mojo/core/ip_address.proto\022\tmojo.core\"" +
      "\023\n\004IPv4\022\013\n\003val\030\001 \001(\r\"\023\n\004IPv6\022\013\n\003val\030\001 \001(" +
      "\004B[\n\026org.mojolang.mojo.coreB\016IpAddressPr" +
      "otoP\001Z/github.com/mojo-lang/core/go/pkg/" +
      "mojo/core;coreb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_core_IPv4_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_core_IPv4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_IPv4_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_mojo_core_IPv6_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_core_IPv6_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_IPv6_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
