// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

/**
 * Protobuf type {@code mojo.core.MultiStringMap}
 */
public final class MultiStringMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.core.MultiStringMap)
    MultiStringMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultiStringMap.newBuilder() to construct.
  private MultiStringMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultiStringMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MultiStringMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MultiStringMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              vals_ = com.google.protobuf.MapField.newMapField(
                  ValsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>
            vals__ = input.readMessage(
                ValsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            vals_.getMutableMap().put(
                vals__.getKey(), vals__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetVals();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.core.MultiStringMap.class, org.mojolang.mojo.core.MultiStringMap.Builder.class);
  }

  public interface StringValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mojo.core.MultiStringMap.StringValues)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string vals = 1;</code>
     * @return A list containing the vals.
     */
    java.util.List<java.lang.String>
        getValsList();
    /**
     * <code>repeated string vals = 1;</code>
     * @return The count of vals.
     */
    int getValsCount();
    /**
     * <code>repeated string vals = 1;</code>
     * @param index The index of the element to return.
     * @return The vals at the given index.
     */
    java.lang.String getVals(int index);
    /**
     * <code>repeated string vals = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the vals at the given index.
     */
    com.google.protobuf.ByteString
        getValsBytes(int index);
  }
  /**
   * Protobuf type {@code mojo.core.MultiStringMap.StringValues}
   */
  public static final class StringValues extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mojo.core.MultiStringMap.StringValues)
      StringValuesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StringValues.newBuilder() to construct.
    private StringValues(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StringValues() {
      vals_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StringValues();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StringValues(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                vals_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              vals_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          vals_ = vals_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_StringValues_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_StringValues_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.core.MultiStringMap.StringValues.class, org.mojolang.mojo.core.MultiStringMap.StringValues.Builder.class);
    }

    public static final int VALS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList vals_;
    /**
     * <code>repeated string vals = 1;</code>
     * @return A list containing the vals.
     */
    public com.google.protobuf.ProtocolStringList
        getValsList() {
      return vals_;
    }
    /**
     * <code>repeated string vals = 1;</code>
     * @return The count of vals.
     */
    public int getValsCount() {
      return vals_.size();
    }
    /**
     * <code>repeated string vals = 1;</code>
     * @param index The index of the element to return.
     * @return The vals at the given index.
     */
    public java.lang.String getVals(int index) {
      return vals_.get(index);
    }
    /**
     * <code>repeated string vals = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the vals at the given index.
     */
    public com.google.protobuf.ByteString
        getValsBytes(int index) {
      return vals_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < vals_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vals_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < vals_.size(); i++) {
          dataSize += computeStringSizeNoTag(vals_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mojolang.mojo.core.MultiStringMap.StringValues)) {
        return super.equals(obj);
      }
      org.mojolang.mojo.core.MultiStringMap.StringValues other = (org.mojolang.mojo.core.MultiStringMap.StringValues) obj;

      if (!getValsList()
          .equals(other.getValsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValsCount() > 0) {
        hash = (37 * hash) + VALS_FIELD_NUMBER;
        hash = (53 * hash) + getValsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mojolang.mojo.core.MultiStringMap.StringValues parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mojolang.mojo.core.MultiStringMap.StringValues prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mojo.core.MultiStringMap.StringValues}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mojo.core.MultiStringMap.StringValues)
        org.mojolang.mojo.core.MultiStringMap.StringValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_StringValues_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_StringValues_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mojolang.mojo.core.MultiStringMap.StringValues.class, org.mojolang.mojo.core.MultiStringMap.StringValues.Builder.class);
      }

      // Construct using org.mojolang.mojo.core.MultiStringMap.StringValues.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vals_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_StringValues_descriptor;
      }

      @java.lang.Override
      public org.mojolang.mojo.core.MultiStringMap.StringValues getDefaultInstanceForType() {
        return org.mojolang.mojo.core.MultiStringMap.StringValues.getDefaultInstance();
      }

      @java.lang.Override
      public org.mojolang.mojo.core.MultiStringMap.StringValues build() {
        org.mojolang.mojo.core.MultiStringMap.StringValues result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mojolang.mojo.core.MultiStringMap.StringValues buildPartial() {
        org.mojolang.mojo.core.MultiStringMap.StringValues result = new org.mojolang.mojo.core.MultiStringMap.StringValues(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          vals_ = vals_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vals_ = vals_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mojolang.mojo.core.MultiStringMap.StringValues) {
          return mergeFrom((org.mojolang.mojo.core.MultiStringMap.StringValues)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mojolang.mojo.core.MultiStringMap.StringValues other) {
        if (other == org.mojolang.mojo.core.MultiStringMap.StringValues.getDefaultInstance()) return this;
        if (!other.vals_.isEmpty()) {
          if (vals_.isEmpty()) {
            vals_ = other.vals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValsIsMutable();
            vals_.addAll(other.vals_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.mojolang.mojo.core.MultiStringMap.StringValues parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.mojolang.mojo.core.MultiStringMap.StringValues) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList vals_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          vals_ = new com.google.protobuf.LazyStringArrayList(vals_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @return A list containing the vals.
       */
      public com.google.protobuf.ProtocolStringList
          getValsList() {
        return vals_.getUnmodifiableView();
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @return The count of vals.
       */
      public int getValsCount() {
        return vals_.size();
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @param index The index of the element to return.
       * @return The vals at the given index.
       */
      public java.lang.String getVals(int index) {
        return vals_.get(index);
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the vals at the given index.
       */
      public com.google.protobuf.ByteString
          getValsBytes(int index) {
        return vals_.getByteString(index);
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @param index The index to set the value at.
       * @param value The vals to set.
       * @return This builder for chaining.
       */
      public Builder setVals(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValsIsMutable();
        vals_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @param value The vals to add.
       * @return This builder for chaining.
       */
      public Builder addVals(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValsIsMutable();
        vals_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @param values The vals to add.
       * @return This builder for chaining.
       */
      public Builder addAllVals(
          java.lang.Iterable<java.lang.String> values) {
        ensureValsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vals_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVals() {
        vals_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string vals = 1;</code>
       * @param value The bytes of the vals to add.
       * @return This builder for chaining.
       */
      public Builder addValsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureValsIsMutable();
        vals_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mojo.core.MultiStringMap.StringValues)
    }

    // @@protoc_insertion_point(class_scope:mojo.core.MultiStringMap.StringValues)
    private static final org.mojolang.mojo.core.MultiStringMap.StringValues DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mojolang.mojo.core.MultiStringMap.StringValues();
    }

    public static org.mojolang.mojo.core.MultiStringMap.StringValues getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringValues>
        PARSER = new com.google.protobuf.AbstractParser<StringValues>() {
      @java.lang.Override
      public StringValues parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringValues(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StringValues> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringValues> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MultiStringMap.StringValues getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int VALS_FIELD_NUMBER = 1;
  private static final class ValsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>newDefaultInstance(
                org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_ValsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.mojolang.mojo.core.MultiStringMap.StringValues.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> vals_;
  private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>
  internalGetVals() {
    if (vals_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValsDefaultEntryHolder.defaultEntry);
    }
    return vals_;
  }

  public int getValsCount() {
    return internalGetVals().getMap().size();
  }
  /**
   * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
   */

  @java.lang.Override
  public boolean containsVals(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetVals().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> getVals() {
    return getValsMap();
  }
  /**
   * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> getValsMap() {
    return internalGetVals().getMap();
  }
  /**
   * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
   */
  @java.lang.Override

  public org.mojolang.mojo.core.MultiStringMap.StringValues getValsOrDefault(
      java.lang.String key,
      org.mojolang.mojo.core.MultiStringMap.StringValues defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> map =
        internalGetVals().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
   */
  @java.lang.Override

  public org.mojolang.mojo.core.MultiStringMap.StringValues getValsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> map =
        internalGetVals().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetVals(),
        ValsDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> entry
         : internalGetVals().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>
      vals__ = ValsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, vals__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.core.MultiStringMap)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.core.MultiStringMap other = (org.mojolang.mojo.core.MultiStringMap) obj;

    if (!internalGetVals().equals(
        other.internalGetVals())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetVals().getMap().isEmpty()) {
      hash = (37 * hash) + VALS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetVals().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.core.MultiStringMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.core.MultiStringMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.core.MultiStringMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.core.MultiStringMap)
      org.mojolang.mojo.core.MultiStringMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetVals();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableVals();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.core.MultiStringMap.class, org.mojolang.mojo.core.MultiStringMap.Builder.class);
    }

    // Construct using org.mojolang.mojo.core.MultiStringMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableVals().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.core.BoxedProto.internal_static_mojo_core_MultiStringMap_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MultiStringMap getDefaultInstanceForType() {
      return org.mojolang.mojo.core.MultiStringMap.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MultiStringMap build() {
      org.mojolang.mojo.core.MultiStringMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MultiStringMap buildPartial() {
      org.mojolang.mojo.core.MultiStringMap result = new org.mojolang.mojo.core.MultiStringMap(this);
      int from_bitField0_ = bitField0_;
      result.vals_ = internalGetVals();
      result.vals_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.core.MultiStringMap) {
        return mergeFrom((org.mojolang.mojo.core.MultiStringMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.core.MultiStringMap other) {
      if (other == org.mojolang.mojo.core.MultiStringMap.getDefaultInstance()) return this;
      internalGetMutableVals().mergeFrom(
          other.internalGetVals());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.core.MultiStringMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.core.MultiStringMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> vals_;
    private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>
    internalGetVals() {
      if (vals_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValsDefaultEntryHolder.defaultEntry);
      }
      return vals_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>
    internalGetMutableVals() {
      onChanged();;
      if (vals_ == null) {
        vals_ = com.google.protobuf.MapField.newMapField(
            ValsDefaultEntryHolder.defaultEntry);
      }
      if (!vals_.isMutable()) {
        vals_ = vals_.copy();
      }
      return vals_;
    }

    public int getValsCount() {
      return internalGetVals().getMap().size();
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */

    @java.lang.Override
    public boolean containsVals(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetVals().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> getVals() {
      return getValsMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> getValsMap() {
      return internalGetVals().getMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */
    @java.lang.Override

    public org.mojolang.mojo.core.MultiStringMap.StringValues getValsOrDefault(
        java.lang.String key,
        org.mojolang.mojo.core.MultiStringMap.StringValues defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> map =
          internalGetVals().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */
    @java.lang.Override

    public org.mojolang.mojo.core.MultiStringMap.StringValues getValsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> map =
          internalGetVals().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearVals() {
      internalGetMutableVals().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */

    public Builder removeVals(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableVals().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues>
    getMutableVals() {
      return internalGetMutableVals().getMutableMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */
    public Builder putVals(
        java.lang.String key,
        org.mojolang.mojo.core.MultiStringMap.StringValues value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableVals().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .mojo.core.MultiStringMap.StringValues&gt; vals = 1;</code>
     */

    public Builder putAllVals(
        java.util.Map<java.lang.String, org.mojolang.mojo.core.MultiStringMap.StringValues> values) {
      internalGetMutableVals().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.core.MultiStringMap)
  }

  // @@protoc_insertion_point(class_scope:mojo.core.MultiStringMap)
  private static final org.mojolang.mojo.core.MultiStringMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.core.MultiStringMap();
  }

  public static org.mojolang.mojo.core.MultiStringMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultiStringMap>
      PARSER = new com.google.protobuf.AbstractParser<MultiStringMap>() {
    @java.lang.Override
    public MultiStringMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MultiStringMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MultiStringMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultiStringMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.core.MultiStringMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

