// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/value.proto

package org.mojolang.mojo.core;

public interface ObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Object)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .mojo.core.Value&gt; values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; values = 1;</code>
   */
  boolean containsValues(
      java.lang.String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.mojolang.mojo.core.Value>
  getValues();
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; values = 1;</code>
   */
  java.util.Map<java.lang.String, org.mojolang.mojo.core.Value>
  getValuesMap();
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; values = 1;</code>
   */

  org.mojolang.mojo.core.Value getValuesOrDefault(
      java.lang.String key,
      org.mojolang.mojo.core.Value defaultValue);
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; values = 1;</code>
   */

  org.mojolang.mojo.core.Value getValuesOrThrow(
      java.lang.String key);
}
