// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/percentage.proto

package org.mojolang.mojo.core;

public final class PercentageProto {
  private PercentageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Percentage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Percentage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032mojo/core/percentage.proto\022\tmojo.core\"" +
      "\033\n\nPercentage\022\r\n\005value\030\001 \001(\005B\\\n\026org.mojo" +
      "lang.mojo.coreB\017PercentageProtoP\001Z/githu" +
      "b.com/mojo-lang/core/go/pkg/mojo/core;co" +
      "reb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_core_Percentage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_core_Percentage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Percentage_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
