// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/pixel.proto

package org.mojolang.mojo.core;

public interface PixelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Pixel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
