// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/integer.proto

package org.mojolang.mojo.core;

public interface PositiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Positive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 val = 1;</code>
   * @return The val.
   */
  long getVal();
}
