// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/url.proto

package org.mojolang.mojo.core;

public final class UrlProto {
  private UrlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Url_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Url_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Url_Authority_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Url_Authority_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Url_Query_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Url_Query_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Url_Query_Strings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Url_Query_Strings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Url_Query_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Url_Query_ValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023mojo/core/url.proto\022\tmojo.core\"\347\002\n\003Url" +
      "\022\016\n\006scheme\030\001 \001(\t\022+\n\tauthority\030\002 \001(\0132\030.mo" +
      "jo.core.Url.Authority\022\014\n\004path\030\003 \001(\t\022#\n\005q" +
      "uery\030\005 \001(\0132\024.mojo.core.Url.Query\022\020\n\010frag" +
      "ment\030\007 \001(\t\032:\n\tAuthority\022\021\n\tuser_info\030\001 \001" +
      "(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\003\032\241\001\n\005Query" +
      "\0220\n\006values\030\001 \003(\0132 .mojo.core.Url.Query.V" +
      "aluesEntry\032\031\n\007Strings\022\016\n\006values\030\001 \003(\t\032K\n" +
      "\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022+\n\005value\030\002 \001(\013" +
      "2\034.mojo.core.Url.Query.Strings:\0028\001BU\n\026or" +
      "g.mojolang.mojo.coreB\010UrlProtoP\001Z/github" +
      ".com/mojo-lang/core/go/pkg/mojo/core;cor" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_core_Url_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_core_Url_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Url_descriptor,
        new java.lang.String[] { "Scheme", "Authority", "Path", "Query", "Fragment", });
    internal_static_mojo_core_Url_Authority_descriptor =
      internal_static_mojo_core_Url_descriptor.getNestedTypes().get(0);
    internal_static_mojo_core_Url_Authority_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Url_Authority_descriptor,
        new java.lang.String[] { "UserInfo", "Host", "Port", });
    internal_static_mojo_core_Url_Query_descriptor =
      internal_static_mojo_core_Url_descriptor.getNestedTypes().get(1);
    internal_static_mojo_core_Url_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Url_Query_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_core_Url_Query_Strings_descriptor =
      internal_static_mojo_core_Url_Query_descriptor.getNestedTypes().get(0);
    internal_static_mojo_core_Url_Query_Strings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Url_Query_Strings_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_core_Url_Query_ValuesEntry_descriptor =
      internal_static_mojo_core_Url_Query_descriptor.getNestedTypes().get(1);
    internal_static_mojo_core_Url_Query_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Url_Query_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
