// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/value.proto

package org.mojolang.mojo.core;

public final class ValueProto {
  private ValueProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Object_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Object_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Values_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Values_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_core_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_core_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025mojo/core/value.proto\022\tmojo.core\"x\n\006Ob" +
      "ject\022-\n\006values\030\001 \003(\0132\035.mojo.core.Object." +
      "ValuesEntry\032?\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\037\n\005value\030\002 \001(\0132\020.mojo.core.Value:\0028\001\"*\n\006" +
      "Values\022 \n\006values\030\001 \003(\0132\020.mojo.core.Value" +
      "\"\267\001\n\005Value\022\'\n\nvalues_val\030\001 \001(\0132\021.mojo.co" +
      "re.ValuesH\000\022\'\n\nobject_val\030\002 \001(\0132\021.mojo.c" +
      "ore.ObjectH\000\022\022\n\010bool_val\030\003 \001(\010H\000\022\023\n\tint6" +
      "4_val\030\004 \001(\003H\000\022\024\n\ndouble_val\030\005 \001(\001H\000\022\024\n\ns" +
      "tring_val\030\007 \001(\tH\000B\007\n\005valueBW\n\026org.mojola" +
      "ng.mojo.coreB\nValueProtoP\001Z/github.com/m" +
      "ojo-lang/core/go/pkg/mojo/core;coreb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_core_Object_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_core_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Object_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_core_Object_ValuesEntry_descriptor =
      internal_static_mojo_core_Object_descriptor.getNestedTypes().get(0);
    internal_static_mojo_core_Object_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Object_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_core_Values_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_core_Values_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Values_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_core_Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mojo_core_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_core_Value_descriptor,
        new java.lang.String[] { "ValuesVal", "ObjectVal", "BoolVal", "Int64Val", "DoubleVal", "StringVal", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
