// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/value.proto

package org.mojolang.mojo.core;

public interface ValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Values)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.core.Value values = 1;</code>
   */
  java.util.List<org.mojolang.mojo.core.Value> 
      getValuesList();
  /**
   * <code>repeated .mojo.core.Value values = 1;</code>
   */
  org.mojolang.mojo.core.Value getValues(int index);
  /**
   * <code>repeated .mojo.core.Value values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .mojo.core.Value values = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.core.ValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .mojo.core.Value values = 1;</code>
   */
  org.mojolang.mojo.core.ValueOrBuilder getValuesOrBuilder(
      int index);
}
